name: Deploy Kong changes to PRD

on:
  push:
    branches:
      - main
    paths:
      - PRD/kong/kong.yaml
      - .github/workflows/deploy-kong-PRD.yaml

jobs:

#  this job is useful to debug workflows, see https://github.com/mheap/debug-artifact
#  debug-artifacts:
#    name: Upload Debug Artifacts
#    runs-on: ubuntu-latest
#    steps:
#      - name: Upload Debug Artifacts
#        uses: mheap/debug-artifact@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-kong:
    name: Deploy Kong to PRD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.26.0'
          wrapper: false

      - name: deck sync
        run: |
          deck sync --select-tag platform-repo-managed \
              -s PRD/kong/kong.yaml \
              --konnect-runtime-group-name KongAir-PRD \
              --konnect-token ${{ secrets.KONNECT_PAT }}
