networks:
  kong-edu-net:
    name: kong-edu-net
    driver: bridge
    external: false
      
services:
 kongair-experience:
  image: kongedu/kongair-experience:1.0
  platform: ${PLATFORM:-linux/amd64}
  container_name: kongair-experience
  hostname: experience.kongair
  restart: on-failure
  networks:
    - kong-edu-net
  ports:
   - 5050:4000

 kongair-customers:
  image: kongedu/kongair-customers:1.0
  platform: ${PLATFORM:-linux/amd64}
  container_name: kongair-customers
  hostname: customers.kongair
  restart: on-failure
  networks:
    - kong-edu-net
  ports:
   - 5051:3000

 kongair-flights:
  image: kongedu/kongair-flights:1.0
  platform: ${PLATFORM:-linux/amd64}
  container_name: kongair-flights
  hostname: flights.kongair
  restart: on-failure
  networks:
    - kong-edu-net
  ports:
   - 5052:8080

 kongair-routes:
  image: kongedu/kongair-routes:1.0
  platform: ${PLATFORM:-linux/amd64}
  container_name: kongair-routes
  hostname: routes.kongair
  restart: on-failure
  networks:
    - kong-edu-net
  ports:
   - 5053:8080

 kongair-bookings:
  image: kongedu/kongair-bookings:1.0
  platform: ${PLATFORM:-linux/amd64}
  container_name: kongair-bookings
  hostname: bookings.kongair
  restart: on-failure
  networks:
    - kong-edu-net
  ports:
   - 5054:3000