version: "3"

networks:
  kong-net:
    external: true

services:
 kongair-flights:
  image: kongair-flights:1.0
  container_name: kongair-flights
  hostname: flights.kongair
  restart: on-failure
  networks:
    - kong-net
  ports:
   - 8080:8080

 kongair-routes:
  image: kongair-routes:1.0
  container_name: kongair-routes
  hostname: routes.kongair
  restart: on-failure
  networks:
    - kong-net
  ports:
   - 8081:8080

 kongair-bookings:
  image: kongair-bookings:1.0
  container_name: kongair-bookings
  hostname: bookings.kongair
  restart: on-failure
  networks:
    - kong-net
  ports:
   - 8082:3000