// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package models

// Route defines model for Route.
type Route struct {
	AvgDuration int    `json:"avg_duration"`
	Destination string `json:"destination"`
	Id          string `json:"id"`
	Origin      string `json:"origin"`
}

// GetRoutesParams defines parameters for GetRoutes.
type GetRoutesParams struct {
	// Origin filter by origin
	Origin *[]string `form:"origin,omitempty" json:"origin,omitempty"`
}
