name: Deploy Kong changes to PRD

on:
  push:
    branches:
      - main
    paths:
      - PRD/kong/kong.yaml
      - .github/workflows/deploy-kong-PRD.yaml
  workflow_dispatch:

jobs:

#  this job is useful to debug workflows, see https://github.com/mheap/debug-artifact
#  debug-artifacts:
#    name: Upload Debug Artifacts
#    runs-on: ubuntu-latest
#    steps:
#      - name: Upload Debug Artifacts
#        uses: mheap/debug-artifact@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-kong:
    name: Deploy Kong to PRD
    runs-on: ubuntu-latest
    env:
      DEPLOY_TARGET: KONNECT

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.38.0'
          wrapper: false

      - name: deck sync konnect
        if: env.DEPLOY_TARGET == 'KONNECT' || env.DEPLOY_TARGET == ''
        run: |
           deck gateway sync --select-tag platform-repo-managed \
               --konnect-control-plane-name ${{ env.KONNECT_CP_NAME }}\
               --konnect-token ${{ secrets.KONNECT_PAT }} \
               --konnect-addr ${{ env.KONNECT_ADDR }} \
               PRD/kong/kong.yaml

      - name: deck sync Kong EE
        if: env.DEPLOY_TARGET == 'EE'
        run: |
            deck gateway sync --select-tag platform-repo-managed \
                --kong-addr ${{ env.KONG_EE_ADMIN_API }} \
                PRD/kong/kong.yaml
      
      - name: deck sync Kong Ingress Controller
        if: env.DEPLOY_TARGET == 'KIC'
        run: |
            deck file kong2kic --select-tag platform-repo-managed \
                -s PRD/kong/kong.yaml | kubectl apply -f -
