name: Deploy Customers API to Kong

on:
  # push:
  #   branches:
  #     - main
  #     - feat/digenable
  #   paths:
  #      - '.github/artifacts/customer/kong.yaml'

  workflow_dispatch:

jobs:
  deploy-api-to-kong:
    name: Deploy Customer API to Kong
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.40.3'
          wrapper: false

      - name: Validate connectivity to Konnect
        run: |
          deck gateway ping \
          --konnect-control-plane-name shrikanth-cp \
          --konnect-token ${{ secrets.KONNECT_PAT }} \
          --konnect-addr $KONNECT_ADDR_EU

      - name: Backup current Kong Configuration
        run: |
          deck gateway dump --select-tag sales --select-tag customer \
           --output-file sales/customer/kong/.generated/backup.yaml \
           --konnect-control-plane-name $KONNECT_INTERNAL_CP \
           --konnect-token ${{ secrets.KONNECT_PAT }} \
           --konnect-addr $KONNECT_ADDR_EU
      
      - name: Apply Configuration to Kong
        run: |
          deck gateway sync --select-tag sales  \
           .github/artifacts/customer/kong.yaml \
            --konnect-control-plane-name $KONNECT_INTERNAL_CP \
            --konnect-token ${{ secrets.KONNECT_PAT }} \
            --konnect-addr $KONNECT_ADDR_EU


      
