name: Build Docker Images

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'PRD/**'
      - 'platform/kong/.generated/kong.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - dir: flight-data
            name: flights
          - dir: flight-data
            name: routes
          - dir: sales
            name: bookings
          - dir: sales
            name: customer
          - dir: .
            name: experience
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "${{ matrix.app.dir }}/${{ matrix.app.name }}"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: kongedu/kongair-${{ matrix.app.name }}:latest
